"""Clearly labeled sample records for local UI development."""

from datetime import UTC, date, datetime

from job_recommendation_agent.domain.models import EmploymentType, Job


def demo_jobs() -> list[Job]:
    """Return comprehensive sample jobs from all career portal networks."""

    return [
        # Arbeitnow Portal Network
        Job(
            id="arbeitnow-berlin-ml-intern-001",
            title="Machine Learning Intern",
            company="Tech Innovations GmbH",
            location="Berlin, Germany",
            employment_type=EmploymentType.INTERNSHIP,
            description="Support a data team with model evaluation and analytics prototypes. Work on cutting-edge ML models.",
            skills=["Python", "Pandas", "Machine Learning", "TensorFlow"],
            source_name="Arbeitnow Portal Network",
            source_url="https://www.arbeitnow.com/jobs",
            posted_date=date(2026, 7, 15),
            posted_at=datetime(2026, 7, 15, 9, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        Job(
            id="arbeitnow-munich-data-working-student-001",
            title="Working Student Data & AI",
            company="Data Systems AG",
            location="Munich, Germany",
            employment_type=EmploymentType.WORKING_STUDENT,
            description="Build reporting workflows and assist with responsible AI experiments.",
            skills=["Python", "SQL", "Power BI", "Analytics"],
            source_name="Arbeitnow Portal Network",
            source_url="https://www.arbeitnow.com/jobs",
            posted_date=date(2026, 7, 14),
            posted_at=datetime(2026, 7, 14, 10, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
        Job(
            id="arbeitnow-hamburg-graduate-engineer-001",
            title="Graduate Software Engineer",
            company="Commerce Solutions SE",
            location="Hamburg, Germany",
            employment_type=EmploymentType.GRADUATE,
            description="Join a graduate rotation working on reliable Python services and cloud infrastructure.",
            skills=["Python", "APIs", "Git", "Cloud"],
            source_name="Arbeitnow Portal Network",
            source_url="https://www.arbeitnow.com/jobs",
            posted_date=date(2026, 7, 13),
            posted_at=datetime(2026, 7, 13, 14, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        Job(
            id="arbeitnow-cologne-data-intern-001",
            title="Data Analytics Internship",
            company="Insights Analytics GmbH",
            location="Cologne, Germany",
            employment_type=EmploymentType.INTERNSHIP,
            description="Join our analytics team to build dashboards and analyze customer behavior data.",
            skills=["SQL", "Tableau", "Python", "Data Analysis"],
            source_name="Arbeitnow Portal Network",
            source_url="https://www.arbeitnow.com/jobs",
            posted_date=date(2026, 7, 12),
            posted_at=datetime(2026, 7, 12, 11, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
        Job(
            id="arbeitnow-frankfurt-thesis-001",
            title="Master Thesis - AI for Supply Chain Optimization",
            company="Logistics Innovation GmbH",
            location="Frankfurt, Germany",
            employment_type=EmploymentType.THESIS,
            description="Develop AI algorithms to optimize supply chain operations. 6-month thesis project.",
            skills=["Machine Learning", "Python", "Operations Research", "AI"],
            source_name="Arbeitnow Portal Network",
            source_url="https://www.arbeitnow.com/jobs",
            posted_date=date(2026, 7, 11),
            posted_at=datetime(2026, 7, 11, 15, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        # Bosch Career Portal
        Job(
            id="bosch-stuttgart-intern-data-001",
            title="Data Science Intern - Automotive AI",
            company="Bosch Group",
            location="Stuttgart, Germany",
            employment_type=EmploymentType.INTERNSHIP,
            description="Develop machine learning solutions for autonomous vehicles and smart sensors.",
            skills=["Python", "Machine Learning", "Data Science", "C++"],
            source_name="Bosch Career Portal",
            source_url="https://www.bosch.com/careers",
            posted_date=date(2026, 7, 14),
            posted_at=datetime(2026, 7, 14, 8, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        Job(
            id="bosch-berlin-working-student-001",
            title="Working Student - Software Development",
            company="Bosch Group",
            location="Berlin, Germany",
            employment_type=EmploymentType.WORKING_STUDENT,
            description="Support backend development for industrial IoT platforms using modern cloud technologies.",
            skills=["Java", "Spring Boot", "Cloud", "Kubernetes"],
            source_name="Bosch Career Portal",
            source_url="https://www.bosch.com/careers",
            posted_date=date(2026, 7, 13),
            posted_at=datetime(2026, 7, 13, 9, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
        Job(
            id="bosch-munich-graduate-001",
            title="Graduate Program - Digital Transformation",
            company="Bosch Group",
            location="Munich, Germany",
            employment_type=EmploymentType.GRADUATE,
            description="2-year rotation program across different business units focusing on digital innovation.",
            skills=["Software Engineering", "Project Management", "Business Analysis"],
            source_name="Bosch Career Portal",
            source_url="https://www.bosch.com/careers",
            posted_date=date(2026, 7, 12),
            posted_at=datetime(2026, 7, 12, 10, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        Job(
            id="bosch-hamburg-thesis-001",
            title="Master Thesis - IoT Security",
            company="Bosch Group",
            location="Hamburg, Germany",
            employment_type=EmploymentType.THESIS,
            description="Research and develop security protocols for connected industrial devices.",
            skills=["Cybersecurity", "IoT", "C", "Python"],
            source_name="Bosch Career Portal",
            source_url="https://www.bosch.com/careers",
            posted_date=date(2026, 7, 11),
            posted_at=datetime(2026, 7, 11, 11, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        # Continental Career Portal
        Job(
            id="continental-hannover-intern-001",
            title="Software Engineering Intern",
            company="Continental AG",
            location="Hannover, Germany",
            employment_type=EmploymentType.INTERNSHIP,
            description="Develop embedded systems for automotive safety and autonomous driving.",
            skills=["C++", "Embedded Systems", "Linux", "AUTOSAR"],
            source_name="Continental Career Portal",
            source_url="https://www.continental.com/careers",
            posted_date=date(2026, 7, 14),
            posted_at=datetime(2026, 7, 14, 9, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        Job(
            id="continental-cologne-working-student-001",
            title="Working Student - Quality Assurance",
            company="Continental AG",
            location="Cologne, Germany",
            employment_type=EmploymentType.WORKING_STUDENT,
            description="Test and validate tire monitoring systems and sensor technologies.",
            skills=["Testing", "Python", "SQL", "Quality Assurance"],
            source_name="Continental Career Portal",
            source_url="https://www.continental.com/careers",
            posted_date=date(2026, 7, 13),
            posted_at=datetime(2026, 7, 13, 10, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
        Job(
            id="continental-frankfurt-graduate-001",
            title="Graduate Program - Engineering Track",
            company="Continental AG",
            location="Frankfurt, Germany",
            employment_type=EmploymentType.GRADUATE,
            description="Join our engineering excellence program with rotations in R&D and manufacturing.",
            skills=["Engineering", "Project Management", "Automotive", "Problem Solving"],
            source_name="Continental Career Portal",
            source_url="https://www.continental.com/careers",
            posted_date=date(2026, 7, 12),
            posted_at=datetime(2026, 7, 12, 11, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        # Amazon Jobs Portal
        Job(
            id="amazon-berlin-internship-001",
            title="Software Development Intern - AWS",
            company="Amazon",
            location="Berlin, Germany",
            employment_type=EmploymentType.INTERNSHIP,
            description="Build cloud-native applications and tools for AWS infrastructure platforms.",
            skills=["Java", "Python", "AWS", "Microservices"],
            source_name="Amazon Jobs Portal",
            source_url="https://www.amazon.jobs",
            posted_date=date(2026, 7, 15),
            posted_at=datetime(2026, 7, 15, 8, tzinfo=UTC),
            is_remote=False,
            is_demo=True,
        ),
        Job(
            id="amazon-luxembourg-graduate-001",
            title="Graduate Software Engineer - Logistics",
            company="Amazon",
            location="Luxembourg",
            employment_type=EmploymentType.GRADUATE,
            description="Optimize logistics networks using machine learning and distributed systems.",
            skills=["Python", "Machine Learning", "Java", "Big Data"],
            source_name="Amazon Jobs Portal",
            source_url="https://www.amazon.jobs",
            posted_date=date(2026, 7, 14),
            posted_at=datetime(2026, 7, 14, 9, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
        Job(
            id="amazon-dublin-data-intern-001",
            title="Data Scientist Intern",
            company="Amazon",
            location="Dublin, Ireland",
            employment_type=EmploymentType.INTERNSHIP,
            description="Analyze petabyte-scale datasets to drive business intelligence and recommendations.",
            skills=["Python", "SQL", "Spark", "Data Analysis"],
            source_name="Amazon Jobs Portal",
            source_url="https://www.amazon.jobs",
            posted_date=date(2026, 7, 13),
            posted_at=datetime(2026, 7, 13, 10, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
        Job(
            id="amazon-munich-working-student-001",
            title="Working Student - Product Management",
            company="Amazon",
            location="Munich, Germany",
            employment_type=EmploymentType.WORKING_STUDENT,
            description="Support product teams in strategy and development of EU marketplace features.",
            skills=["Business Analysis", "Data Analysis", "Project Management"],
            source_name="Amazon Jobs Portal",
            source_url="https://www.amazon.jobs",
            posted_date=date(2026, 7, 12),
            posted_at=datetime(2026, 7, 12, 11, tzinfo=UTC),
            is_remote=True,
            is_demo=True,
        ),
    ]
